### PR TITLE
Issue 241

### LINKED ISSUE #241: Option --results-dir should be used for storing outputs
I have specified the option --results-dir in Dockerfile and I have expected that
the output of rebase-helper will be stored there.

Unfortunately rebase-helper also expects in the directory all package data like patches, sources, etc.

The directory /package_name contains all data for rebases.
~~~
$ docker run -ti -e RH_PACKAGE=preupgrade-assistant -e RH_VERSION=2.1.10 -v /home/phracek/work/programming/docker-rebase-helper/docker_export:/rebase_helper rebasehelper:0.2
total 72
drwxr-xr-x 1 root root  578 Nov  1 09:39 .
drwxr-xr-x 1 root root  244 Nov  1 09:40 ..
drwxr-xr-x 1 root root  138 Nov  1 09:39 .git
-rw-r--r-- 1 root root  103 Nov  1 09:39 .gitignore
-rw-r--r-- 1 root root  255 Nov  1 09:39 check.ini
-rwxr-xr-x 1 root root   90 Nov  1 09:39 check.sh
-rw-r--r-- 1 root root  225 Nov  1 09:39 macros.preupgrade-assistant
-rw-r--r-- 1 root root  619 Nov  1 09:39 preupgrade-assistant-create-group.patch
-rw-r--r-- 1 root root 1725 Nov  1 09:39 preupgrade-assistant-do-not-ship-ui.patch
-rw-r--r-- 1 root root 2620 Nov  1 09:39 preupgrade-assistant-python3-fixes.patch
-rw-r--r-- 1 root root 8591 Nov  1 09:39 preupgrade-assistant.spec
-rw-r--r-- 1 root root  306 Nov  1 09:39 repositories.ini
-rwxr-xr-x 1 root root 2742 Nov  1 09:39 repositories.py
-rw-r--r-- 1 root root  184 Nov  1 09:39 repositories.txt
-rwxr-xr-x 1 root root  218 Nov  1 09:39 rpm.ini
-rwxr-xr-x 1 root root  230 Nov  1 09:39 rpm.sh
-rw-r--r-- 1 root root   55 Nov  1 09:39 rpm.txt
-rw-r--r-- 1 root root   46 Nov  1 09:39 solution.txt
-rw-r--r-- 1 root root   47 Nov  1 09:39 sources
Results directory 'rebase-helper-results' exists, removing it
Rebase-helper version: 0.8.0

Could not find any SPEC file in the current directory '/rebase_helper'
$
~~~

I guess, the code https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/application.py#L106 is wrong.

executing_dir is something different then results_dir.

### PR DESCRIPTION
**Pull request by phracek**
The issue fixes #241 .
If user do not specify --results-dir then results are stored in current working directory.
Otherwise, logs and other stuff is stored in --results-dir directory.

### CODE REVIEW

**Comment by nforro** [comment]
@phracek: First of all, I think you should base the pull requests on top of the master branch, not on top of each other. So this PR should contain only last two commits.

**Comment by nforro** [comment]
@phracek: The last two commits look good, but the problem is not resolved completely - for example [get_rebase_name](https://github.com/rebase-helper/rebase-helper/blob/1809400550d7de77fe1904b807eca8ad9d625311/rebasehelper/specfile.py#L46) function just ignores `Application.results_dir` variable.

Also pylint complains about missing argument to [Application constructor](https://github.com/rebase-helper/rebase-helper/blob/1809400550d7de77fe1904b807eca8ad9d625311/rebasehelper/application.py#L775). I think that part of code can be removed anyway, as `application.py` is not intended to be executed directly.

**Comment by phracek** [comment]
It is weird. I will create a new PR. I don't know what's happened. You are right.

**Comment by nforro** [comment]
@phracek: You don't have to create new PR, just rebase the **issue_241** branch and remove unwanted commits.

**Comment by thozza** [comment]
@phracek additionally the hook should work on the SpecFile object, not get the path to file and to magic on it. This way the SpecFile object will simply ignore any changes.

**Pull request closed without merging**
