### PR TITLE
Propagate build errors to results_store

### PR DESCRIPTION
**Pull request by nforro**
This kind of information is missing in `results_store`.

@skisela: Maybe it could be also displayed in reports, what do you think?

### CODE REVIEW

**Comment by skisela** [comment]
Well the exception message (https://github.com/rebase-helper/rebase-helper/pull/336/files#diff-55e1f3684ba905b1c1f92175ff8187d2R560) which is just slightly different from what you've added to the results_store is already set to be saved to results_store by print_summary() (https://github.com/rebase-helper/rebase-helper/pull/336/files#diff-55e1f3684ba905b1c1f92175ff8187d2R697)

But we can surely add this additional info to the report.

**Comment by skisela** [comment]
Your approach is better without a doubt. The previous one was more messy as the error message could be saved/read more conveniently, than it is in print_summary().

**Comment by nforro** [comment]
The point was mainly to add an information about the stage of failure - was it during srpm or rpm build?

**Comment by skisela** [comment]
Well as far as I understand it, that information is already in the message string passed to the exception. Am I missing something?

**Comment by nforro** [comment]
Right, I didn't realize that. But I still find checking for known key (`source_package_build_error`, `binary_package_build_error`) in `results_store` to be better than parsing exception message.

**Comment by skisela** [comment]
Yes that is what I meant. You can merge it(if you want) and I can modify it to make it match the discussion here.

**Pull request merged**
