### PR TITLE
Improve Travis script part by YAML block style "|".

### PR DESCRIPTION
**Pull request by junaruga**
Improve the long line of the Travis script part.

### CODE REVIEW

**Comment by junaruga** [comment]
Just moment, I want to change the indent from 2 spaces to 4 spaces matching other parts.

**Comment by junaruga** [comment]
OK done.

**Comment by nforro** [comment]
Great, thanks. Could you also rebase to master before merge?

**Comment by junaruga** [comment]
OK just moment.

**Comment by junaruga** [comment]
Thanks for the merging!

**Pull request merged**
