### PR TITLE
Switch to pyproject.toml

### PR DESCRIPTION
**Pull request by nforro**

### CODE REVIEW

**Review by FrNecas — APPROVED** [review]
Wow, really nice simplification, especially of the specfile. Looks good as far as I can tell. We should probably also update this doc page https://rebase-helper.readthedocs.io/en/latest/user_guide/installation.html which refers to setup.py.

**Comment by FrNecas** [comment]
Hm, `Writing plugins` also contains a setup.py example. I am not sure if combination of pyproject with setup.py will work :thinking:

**Comment by nforro** [comment]
Good point, I'll update the documentation. I don't know if entrypoints can be specified in pyproject.toml directly (but I'll find out), but they can be defined in setup.cfg.

**Comment by nforro** [comment]
Updated docs: https://rebase-helper.readthedocs.io/en/pyproject.toml/

**Review by FrNecas — APPROVED** [review]
:+1:

**Pull request merged**
