### PR TITLE
Test packit-as-a-service

### PR DESCRIPTION
**Pull request by nforro**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
We had a bit of issues lately with the service, so please bear with us. Fixing it right now.

**Comment by nforro** [comment]
@TomasTomecek thanks for letting us know, I was just trying to figure out if the problem is on our end.

**Comment by nforro** [comment]
@TomasTomecek any idea what's going on here?

The error looks rather strange:
`There was an error while running the build: Failed to parse SPEC file: error: line 13: Unknown tag:   warnings.warn(msg)`

**Comment by TomasTomecek** [comment]
Hmmm, no idea what went wrong. Trying `packit srpm` locally and it works just fine.

**Pull request closed without merging**
