### PR TITLE
Simplify packit config

### PR DESCRIPTION
**Pull request by jpopelka**
https://packit.dev/docs/configuration/

### CODE REVIEW

**Comment by jpopelka** [comment]
strange, `packit srpm` works ok locally

**Comment by nforro** [comment]
Well, `strictness: veryhigh` obviously comes from `.prospector.yml`, if that tells you anything.

**Comment by nforro** [comment]
I'm not sure what you are trying to accomplish, but both upstream and downstream package name needs to be `rebase-helper`, with the dash. And so does stdist's base-name.

**Comment by jpopelka** [comment]
Both [upstream_package_name](https://packit.dev/docs/configuration/#upstream-package-name) and [downstream_package_name](https://packit.dev/docs/configuration/#downstream-package-name) now default (if not specified) to the name of the git repository, i.e. `rebase-helper` in this case.
So we can omit `downstream_package_name`.
`upstream_package_name` means the PyPI package name which is [rebasehelper](https://pypi.org/project/rebasehelper/) - that's why I changed it.
I changed the stdist's base-name as well because that's what made `packit srpm` work locally after t changing the `upstream_package_name`.

I don't know prospector, but will take a look.

**Comment by nforro** [comment]
> `upstream_package_name` means the PyPI package name which is rebasehelper - that's why I changed it.

But PyPI is not the upstream for the Fedora package, github is. Maybe it doesn't really matter, but I suspect spec file discovery could be affected by it.

**Comment by jpopelka** [comment]
Ok, I've removed `upstream_package_name` too.
`packit srpm` works just fine locally so I have no clue how the prospector (which IMHO lints just python files) is related to this yaml only change and how it can affect srpm build.
Let's leave this to Monday :-)

**Comment by nforro** [comment]
I'm not suggesting prospector has something to do with it, but it looks to me like packit is trying to parse the `.prospector.yml` as a spec file (instead of `rebase-helper.spec`).

**Comment by jpopelka** [comment]
I've returned the `specfile_path` and will take a look at the prospector weirdness later.

**Pull request merged**
