### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by nforro**
This PR adds posibility to automatically generate program documentation from ArgumentParser instance. It introduces Sphinx extension `autoargs`, which is similar to [sphinx-argparse](https://github.com/ribozz/sphinx-argparse), but actually quite different. There is also custom manpage builder `custom-man`, which is needed because default Sphinx manpage builder is not very usable when you want the same source for both html and man.

You can see html output on [readthedocs](http://rebase-helper.readthedocs.io/en/documentation-changes/usage.html).

To see the manpage, run the following in `docs` subdir:
```
make man
man -l _build/man/rebase-helper.1
```

This resolves issue #187.

### CODE REVIEW

**Comment by phracek** [comment]
Looks good to me.

**Comment by nforro** [comment]
@phracek: Thanks.
@thozza: Can you also take a look at this when you have time?

**Comment by thozza** [comment]
@nforro The changes look good. Good job! I have just a small comment. The copyright should be given to Red Hat. At the bottom of the man page I see:
```
COPYRIGHT
       2016, Petr Hracek, Tomas Hozza
```
Can it be changed to something like?
```
COPYRIGHT
       2014-2016, Red Hat
```

**Comment by nforro** [comment]
@thozza: Sure, it's just a matter of changing `copyright` variable in  `docs/conf.py`. That will of course change copyright in html documentation as well.

**Pull request merged**
